### ISSUE TITLE
Appcast does not contain 1.0.5

### ISSUE THREAD

**Issue by suschizu** [ronyfadel/BatteriesReleases#1]
Hello @ronyfadel - I've noticed that the appcast.xml doesn't contain the latest version - 
is this intentional? Best

**Comment by ronyfadel** [comment]
Yes :)
It’s to make sure that 1.0.5 isn’t busted until a few people download it. Once it’s cleared, I’ll update everyone to 1.0.5.

**Comment by suschizu** [comment]
Thanks for the information - happy new year :)
