### ISSUE TITLE
Airpods max battery not reliable and doesn't have any icon.

### ISSUE THREAD

**Issue by pbocek** [ronyfadel/BatteriesReleases#11]
Hello, I'm having issue with my Airpods Max. 

![image](https://user-images.githubusercontent.com/19386789/170219522-6c1b526c-a99e-4546-9899-c04497410434.png)
![image](https://user-images.githubusercontent.com/19386789/170219558-76c151d8-16b0-496f-95ae-1824a5516dc4.png)
Battery level is not synchronised most of the time, and the info is missing icon. Therefor the notification for low battery is not working.

**Comment by pitrisss** [comment]
Any update on this? I bought this app specifically for tracking the airpods.
