### ISSUE TITLE
Homebrew update fails

### ISSUE THREAD

**Issue by kolchurinvv** [ronyfadel/BatteriesReleases#16]
Error: batteries: Download failed on Cask 'batteries' with message: Download failed: https://github.com/ronyfadel/BatteriesReleases/releases/download/v2.2.9/Batteries.dmg
the v2.2.9 tag doesn't have a .dmg package and 2.2.9 isn't listed among releases. please advise

**Comment by atkrv** [comment]
It seems https://github.com/Homebrew/homebrew-cask/pull/171460 should be rolled back.
