### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [ronyfadel/BatteriesReleases#2]
It is sad that the application is only in English - I propose to translate.
I am ready to help in the translation into Russian.

You can do something like this:
https://github.com/mufasaYC/tasks-localization
https://github.com/vidrioapp/vidrio-translations

**Comment by ronyfadel** [comment]
Agreed. I'll start this effort soon!

**Comment by DragonSerW** [comment]
Hi Rony! I can help too.

**Comment by SuperTost100** [comment]
I can help translating in Italian!

**Comment by ronyfadel** [comment]
I've been bumping this way too long, but it's finally here!

The localization folder is at: https://github.com/ronyfadel/BatteriesReleases/tree/master/Localization/

**Comment by Tostware-yt** [comment]
I'll start translating both today!

**Comment by Tostware-yt** [comment]
I've translated mission control plus, how can I upload the file?

**Comment by ronyfadel** [comment]
You can attach it here if you want and I'll add it.

**Comment by Tostware-yt** [comment]
[batteries italian.zip](https://github.com/ronyfadel/BatteriesReleases/files/7839937/batteries.italian.zip)
[mission control plus italian.zip](https://github.com/ronyfadel/BatteriesReleases/files/7839947/mission.control.plus.italian.zip)
here the files of Batteries and Mission Control Plus

**Comment by ronyfadel** [comment]
Thank you @Tostware-yt !

@KovalevArtem @DragonSerW let me know if you can add more locales. I'm pushing out an update in the next week.

**Comment by Tostware-yt** [comment]
Will be released next week also on Setapp?

**Comment by ronyfadel** [comment]
Yes
