### ISSUE TITLE
Big Sur compatability

### ISSUE THREAD

**Issue by Pixelfool** [ronyfadel/BatteriesReleases#3]
In Beta 8 & 9 Batteries does not show up in the menu bar.
I am on Version 2.0.1 from SetApp. I tried uninstalling and installing again. Removing and setting the checkmark does nothing.

**Comment by yonigold1** [comment]
hey any update on when we can expect a release? im so excited its my favourite app of ever! kinda annoying that apple doesn't do it on their own!

**Comment by yonigold1** [comment]
Can we still expect a release before Big Sur drops tomorrow?

**Comment by ronyfadel** [comment]
You can access the pre-released at: https://github.com/ronyfadel/BatteriesReleases/releases/tag/v2.0.2

**Comment by ronyfadel** [comment]
Added: WidgetKit widget + Update menu bar popover

**Comment by yonigold1** [comment]
Just a question for you @ronyfadel can you make the menu bar item work the same as it used to with it looking identical to the stock battery icon and menu drop down then with the other Apple products showing under that? That was why I just bought the app today after using the free trial in catalina.

**Comment by ronyfadel** [comment]
Hey Yoni, the first issue will be fixed soon.
As for the second, I'm pushing an update in hopes of getting it fixed. Please reboot your Mac as well, that might fix it.

**Comment by yonigold1** [comment]
Just updated and restarted and my widgets are blank still this is what they show
<img width="365" alt="Screen Shot 2020-11-19 at 2 57 13 PM" src="https://user-images.githubusercontent.com/34217684/99717530-8376ae00-2a77-11eb-9e84-45ebff4d74c1.png">
